#!/usr/bin/perl -w
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
 
my $len;
my @exclude;

GetOptions(
    'length=s' => \$len,
    'exclude=s@' => \@exclude,
) or die "Usage: $0 --l[ength]  --e[xclude] a-z ' ' "\'" '"' 0-9\n";
 

my $pwd = "";
my $c = "";

while ($len > 0) {
  $c = chr(int(rand(94)) + 32);
  foreach (@exclude) {
    next if $c =~ m/$_/;
  }
  $pwd .= $c;
  $len--;
}

printf("pwd: '%s'\n", $pwd);
