#!/usr/bin/perl -w
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
 
my $len;
my @exclude;

GetOptions(
    'length=s' => \$len,
    'exclude=s{1,}' => \@exclude,
) or die "Usage: $0 --l[ength]  --e[xclude] a-z \"'\" '\"' 0-9\n";
 

my $pwd = "";
my $c = "";
my $pat = "";
my $skip= 0;

while ($len > 0) {
  $c = chr(int(rand(94)) + 32);
  $skip = 0;

  foreach (@exclude) {
    $pat = $_;
    if ($c =~ m/$pat/g) {
      $skip = 1;
    }
  }
  next if $skip;
  $pwd .= $c;
  $len--;
}

printf("pwd: '%s'\n", $pwd);
